// Static build step: assembles templates/ + content/ into the real served
// HTML files (wrangler.jsonc serves the repo root directly, so the output
// of this script IS the deployed site). Run with `npm run build`.
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");

const read = (relPath) => fs.readFileSync(path.join(ROOT, relPath), "utf8");
const tryRead = (relPath) => {
  try {
    return fs.readFileSync(path.join(ROOT, relPath), "utf8");
  } catch {
    return "";
  }
};

const headTpl = read("templates/head.html");
const navTpl = read("templates/nav.html");
const footerTpl = read("templates/footer.html");

const NAV_ACTIVE = "text-black font-bold border-b-2 border-black pb-1";
const NAV_INACTIVE = "text-gray-500 hover:text-black transition-colors font-medium";

function fill(str, vars) {
  return str.replace(/\{\{(\w+)\}\}/g, (m, key) => (key in vars ? vars[key] : m));
}

function renderNav(base, active) {
  const navVars = { BASE: base };
  for (const key of ["home", "directory", "about", "contact"]) {
    navVars[`NAV_${key.toUpperCase()}`] = key === active ? NAV_ACTIVE : NAV_INACTIVE;
  }
  return fill(navTpl, navVars);
}

function renderPage({ base, title, active, bodyPath, scriptPath, outPath }) {
  const head = fill(headTpl, { TITLE: title, BASE: base });
  const nav = renderNav(base, active);
  const body = read(bodyPath);
  const script = tryRead(scriptPath);
  const footer = fill(footerTpl, { BASE: base });

  const doc =
    `<!-- AUTO-GENERATED by scripts/build.js from templates/ + content/. ` +
    `Edit those, then run \`npm run build\` — do not hand-edit this file. -->\n` +
    head + "\n" +
    nav + "\n" +
    body + "\n\n" +
    footer +
    (script ? "\n\n" + script : "") +
    "\n</body>\n</html>\n";

  fs.writeFileSync(path.join(ROOT, outPath), doc, "utf8");
  console.log("built", outPath);
}

// Root pages
const pages = JSON.parse(read("data/pages.json"));
for (const page of pages) {
  const slug = page.path.replace(/\.html$/, "");
  renderPage({
    base: "",
    title: page.title,
    active: page.active,
    bodyPath: `content/${slug}.body.html`,
    scriptPath: `content/${slug}.script.html`,
    outPath: page.path,
  });
}

// Board pages, derived from scholars.json (name -> title, profileLink -> outPath)
const scholars = JSON.parse(read("data/scholars.json"));
for (const scholar of scholars) {
  const outPath = scholar.profileLink;
  const slug = path.basename(outPath, ".html");
  renderPage({
    base: "../",
    title: `${scholar.name} | Academic Profile`,
    active: "directory",
    bodyPath: `content/board/${slug}.body.html`,
    scriptPath: `content/board/${slug}.script.html`,
    outPath,
  });
}

console.log(`Build complete: ${pages.length + scholars.length} pages.`);
